# upload in releases if branch is tagged
deploy:
  provider: releases
  api_key: $APIKEY
  file: rooted_$TRAVIS_COMMIT.zip
  skip_cleanup: true
  on:
    tags: true
all_branches: true

sudo: required
before_install:
 - sudo apt-get update -qyy
 - sudo apt-get install -qyy curl bc make git build-essential
 - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6 /opt/toolchains/arm-eabi-4.6/
script:
# export your own config for example
 - ./build_kernel.sh
 - ./mkbootimg --kernel ./arch/arm/boot/zImage --ramdisk split_img/boot.img-ramdisk.cpio.gz \
               --base 10000000 --pagesize 2048 --kernel_offset 00008000 --ramdisk_offset 01000000 \
               --second_offset 00f00000 --tags_offset 00000100 -o boot.img
 - tar -H ustar -c boot.img > boot.tar
 - md5sum -t boot.tar >> boot.tar
 - mv boot.tar boot.tar.md5
 - zip boot.zip boot.tar.md5
after_script:
 - curl --upload-file boot.zip https://transfer.sh/boot.zip | grep transfer
 
